# Generated by Django 2.2.6 on 2019-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='thumbnail',
            field=models.ImageField(blank=True, default='rec_info_default.png', upload_to=''),
        ),
    ]
